--COMMIT;
--
--ROLLBACK;
--
--SELECT * FROM SALGRADE;
--
--DELETE FROM SALGRADE;
--
--STUDENT, ENROL, SUBJECT 테이블 사용
--1. STUDENT 테이블 조회 쿼리
SELECT * FROM STUDENT;

--2. STUDENT 테이블 레코드 개수 구하기 - 별칭 CNT
SELECT COUNT(*) AS CNT FROM STUDENT;

--3.STUDENT 테이블에서 학번, 이름, 학과 컬럼 조회
SELECT STU_NO,STU_NAME,STU_DEPT FROM STUDENT;

--4.STUDENT 테이블에서 기계과 학생만 조회(조건 -> WHERE)
SELECT *
FROM STUDENT
--WHERE STU_DEPT = '기계' AND STU_GENDER = 'M';
WHERE STU_DEPT IN ('기계');

--5. STUDENT 테이블에서 남자만 검색
SELECT *
FROM STUDENT
WHERE STU_GENDER = 'M';

--6. STUDENT 테이블에서 키(STU_HEIGHT)가 170이상인 학생 조회
SELECT *
FROM STUDENT
WHERE STU_HEIGHT >= 170;

--7. STUDENT 테이블에서 키가 175이상 이거나(OR) 몸무게가 60이상인 학생조회
SELECT *
FROM STUDENT
WHERE STU_HEIGHT >=175 OR STU_WEIGHT >= 60;

--8. STUDENT 테이블에서 키가 170~180 사이의 학생 조회
SELECT *
FROM STUDENT
--WHERE STU_HEIGHT >= 170 AND STU_HEIGHT <=180;
WHERE STU_HEIGHT BETWEEN 170 AND 180;

--9. STUDENT 에서 키가 NULL인 학생 조회
SELECT *
FROM STUDENT
--WHERE STU_HEIGHT IS NULL; 
WHERE STU_HEIGHT IS NOT NULL; --NULL값이 아닌경우만 출력

--10 . STUDENT 테이블에서 기계과 이거나 전기 전자과인 학생을 조회
SELECT *
FROM STUDENT
WHERE STU_DEPT IN ('기계','전기전자');
--WHERE STU_DEPT = '기계' OR STU_DEPT = '전기전자';

--11.STUDENT 테이블에서 남학생의 수 조회
SELECT COUNT(*) AS 남학생수
FROM STUDENT
WHERE STU_GENDER = 'M';

