--1. 각 학년별 학생들의 평균 키를 구하시오.
SELECT GRADE, AVG(HEIGHT) AS 평균키
FROM STUDENT2
GROUP BY GRADE;

--2. 96학번과 97학번 중 가장 키가 큰 학생의 학번, 이름, 아이디, 키를 출력하시오.
-- (학번 : STUDNO 의 첫 두글자)
SELECT STUDNO,NAME,ID,HEIGHT
FROM STUDENT2
WHERE HEIGHT = (
    SELECT MAX(HEIGHT) AS HEIGHT
    FROM STUDENT2
    WHERE SUBSTR(STUDNO,1,2) IN ('96','97')
    );
    
SELECT STUDNO, NAME, ID, S.HEIGHT
FROM STUDENT2 S
INNER JOIN (
    SELECT SUBSTR(STUDNO,1,2) AS HAKBUN, MAX(HEIGHT) AS HEIGHT
    FROM STUDENT2
    WHERE SUBSTR(STUDNO,1,2) IN (96, 97)
    GROUP BY SUBSTR(STUDNO,1,2)
    ORDER BY HEIGHT
) S2 ON SUBSTR(STUDNO,1,2) = HAKBUN AND S.HEIGHT = S2.HEIGHT
WHERE ROWNUM = 1;

SELECT *
FROM STUDENT2
WHERE HEIGHT = (
    SELECT MAX(HEIGHT)
    FROM STUDENT2
    WHERE SUBSTR(STUDNO,1,2) IN (96, 97)
) AND SUBSTR(STUDNO,1,2) IN (96, 97);

SELECT *
FROM STUDENT2 S 
INNER JOIN (
    SELECT MAX(HEIGHT) AS HEIGHT
    FROM STUDENT2
    WHERE SUBSTR(STUDNO,1,2) IN (96, 97)
) S2 ON S.HEIGHT = S2.HEIGHT
WHERE SUBSTR(STUDNO,1,2) IN (96, 97);


--3. 교수의 평균임금이 가장 높은 학과의 학과명, 평균 임금을 출력하시오.
SELECT DNAME,PAY
FROM (
    SELECT D.DNAME, AVG(PAY) AS PAY
    FROM PROFESSOR P
    INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
    GROUP BY D.DNAME
    ORDER BY PAY DESC) WHERE ROWNUM = 1;
    
SELECT DNAME, PAY
FROM DEPARTMENT D
INNER JOIN (
    SELECT DEPTNO, AVG(PAY) AS PAY
    FROM PROFESSOR
    GROUP BY DEPTNO
    ORDER BY PAY DESC
) D2 ON D.DEPTNO = D2.DEPTNO 
WHERE ROWNUM = 1;

--4. 95년~05년 사이에 부임한 교수의 수를 구하시오.
SELECT COUNT(*) AS 교수의수
FROM PROFESSOR
WHERE HIREDATE BETWEEN TO_DATE('95/01/01') AND TO_DATE('05/01/01'); 

SELECT COUNT(*) AS 진짜교수
FROM (
    SELECT *
    FROM PROFESSOR
    WHERE HIREDATE BETWEEN '95/01/01' AND '05/12/31')
WHERE POSITION LIKE '%교수%'
; 

--5. '인문대학'에 소속된 교수들의 목록을 구하시오.
SELECT *
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO 
INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '인문대학';

--6. 각 학년별 키가 가장 큰 학생의 학번, 이름, 학년, 키를 구하시오.
SELECT S.STUDNO,S.NAME,S.GRADE,S.HEIGHT
FROM STUDENT2 S
INNER JOIN ( 
    SELECT GRADE,MAX(HEIGHT) AS HEIGHT
    FROM STUDENT2
    GROUP BY GRADE) S2 ON S.HEIGHT = S2.HEIGHT AND S.GRADE = S2.GRADE;
    
--6-1.각 학과별 몸무게가 가장 적은 학생의 학번, 이름, 학년, 키를 구하시오
SELECT STUDNO, NAME, GRADE, HEIGHT, S2.DNAME , S.WEIGHT
FROM STUDENT2 S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
INNER JOIN (
    SELECT D.DNAME, MIN(WEIGHT) AS WEIGHT
    FROM STUDENT2 S
    INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
    GROUP BY D.DNAME) S2 ON S.WEIGHT = S2.WEIGHT AND D.DNAME = S2.DNAME;
    
    SELECT STUDNO, NAME, GRADE, S.WEIGHT, S2.DEPTNO1
FROM STUDENT2 S
INNER JOIN (
    SELECT DEPTNO1, MIN(WEIGHT) AS WEIGHT
    FROM STUDENT2 S
    INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
    GROUP BY DEPTNO1
)S2 ON S.DEPTNO1 = S2.DEPTNO1 AND S.WEIGHT = S2.WEIGHT;

--6-2. 96학번읭 가장 큰 키 값과 97학번 중 가장 작은 키 값의 차이 구하기 
SELECT 
    (SELECT MAX(HEIGHT) 
    FROM STUDENT2 
    WHERE SUBSTR(STUDNO,1,2) = 96)
    - 
    (SELECT MIN(HEIGHT)AS MIN
    FROM STUDENT2
    WHERE SUBSTR(STUDNO,1,2) = 97) AS 키차이
FROM DUAL;


--7. 78년생 학생들의 성별(남,여) 인원수를 구하시오.

SELECT 
    SUM(DECODE(SUBSTR(JUMIN,7,1), '1', 1, 0))"남자"
    ,SUM(DECODE(SUBSTR(JUMIN,7,1), '2', 1, 0))"여자"
FROM STUDENT2
WHERE SUBSTR(JUMIN,1,2) = 78;

SELECT 
    COUNT(DECODE(SUBSTR(JUMIN,7,1), '1', 1, '남자'))
    ,COUNT(DECODE(SUBSTR(JUMIN,7,1), '2', 1, '여자')) 
FROM STUDENT2
WHERE JUMIN LIKE '78%';


SELECT 
    COUNT(A) AS 남성,
    COUNT(B) AS 여성
FROM(
    SELECT 
    DECODE(SUBSTR(JUMIN,7,1), '1', '남자') AS A
    ,DECODE(SUBSTR(JUMIN,7,1), '2', '여자') AS B
    FROM STUDENT2
    WHERE SUBSTR(JUMIN,1,2) = 78
);