-- 1. 학생 테이블에서 2013년도에 입학한 사람 레코드 출력
SELECT *
FROM STUDENT
WHERE STU_NO LIKE '2013%';

SELECT *
FROM STUDENT
WHERE SUBSTR(STU_NO,1,4) = 2013;
--1-2. 그외학번 모자이크 처리하기
SELECT STU_NAME,STU_DEPT, RPAD(SUBSTR(STU_NO,1,4),8,'*') AS STU_NO
FROM STUDENT;

SELECT RPAD(SUBSTR(STU_NO,1,4),8,'*') AS STU_NO
    ,STU_NAME
    ,STU_DEPT
FROM STUDENT
WHERE SUBSTR(STU_NO,1,4) = 2013;

-- 2. 학생 학번, 이름, 과목명, 점수 출력
SELECT S.STU_NO,STU_NAME,SUB_NAME,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
;

SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
-- 3. 기계공작법 수업을 듣는 학생의 학번, 이름 출력
SELECT *
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_NAME = '기계공작법';

-- 4. 옥한빛의 평균 점수보다 낮은 점수를 받은 학생들의 이름, 과목명, 점수 출력
SELECT S.STU_NAME,SUB_NAME,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE ENR_GRADE < (
    SELECT AVG(ENR_GRADE)
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    WHERE STU_NAME = '옥한빛'
    ) AND STU_NAME !='옥한빛'
ORDER BY ENR_GRADE;

-- 5. 각 부서별 급여 등급이 2등급 이상인 사람의 평균 급여 구하기

SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

SELECT D.DEPTNO,DNAME, AVG(SAL) AS AAA
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO
WHERE GRADE >=2
GROUP BY D.DEPTNO,DNAME
ORDER BY AAA;
