--시간 SYSDATE
SELECT 
    SYSDATE,
    TO_CHAR(SYSDATE , 'YYYY/MM-DD HH24:MI:SS')
FROM DUAL;

SELECT * 
FROM EMP ORDER BY hiredate;

-- 81년 2월 이후 입사
SELECT * 
FROM EMP 
WHERE HIREDATE > '81/02/01'
ORDER BY hiredate;

--81년 1월 부터 82년 6월 이전까지 입사한 사람 출력
SELECT * 
FROM EMP 
WHERE HIREDATE BETWEEN '81/01/01' AND '82/06/01'
ORDER BY hiredate;

SELECT * FROM STUDENT;
--0.각 학과에서 가장 키 큰 학생의 학번, 이름, 키 출력
SELECT S.STU_NO,S.STU_NAME,S.STU_DEPT,S.STU_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, MAX(STU_HEIGHT) AS STU_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) S2 ON S.STU_HEIGHT = S2.STU_HEIGHT AND S.STU_DEPT = S2.STU_DEPT
;



-- 1. 각 부서 별 입사일이 가장 오래된 사원을 한 명씩 선별해 
--사원번호, 사원명, 부서번호, 입사일을 출력하라.
SELECT EMPNO,ENAME,E.DEPTNO,E.HIREDATE
FROM EMP E
INNER JOIN(
    SELECT DEPTNO, MIN(HIREDATE) AS HIREDATE
    FROM EMP E
    WHERE DEPTNO IS NOT NULL
    GROUP BY DEPTNO
)E2 ON E.HIREDATE = E2.HIREDATE AND E.DEPTNO = E2.DEPTNO;

SELECT *
FROM EMP
WHERE (DEPTNO, HIREDATE) IN (
    SELECT DEPTNO, MIN(HIREDATE) AS HDATE
    FROM EMP
    WHERE DEPTNO IS NOT NULL
    GROUP BY DEPTNO
);

SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;
-- 2. 1981년 5월 31일 이후 입사자 중 커미션이 NULL이거나 0인 
--사원의 커미션은 500으로 그렇지 않으면 기존 커미션을 출력하라.
SELECT ENAME,HIREDATE,NVL(COMM,500) AS COMM
FROM (
    SELECT * 
    FROM EMP 
    WHERE HIREDATE > '81/05/31'
    ORDER BY hiredate
    );

SELECT ENAME,HIREDATE,
    DECODE(COMM, NULL, 500, 0, 500, COMM)
FROM EMP
WHERE HIREDATE > TO_DATE('1981/05/31');


-- 3. 1981년 6월 1일 ~ 1981년 12월 31일 입사자 중 
--부서명이 SALES인 사원의 부서번호, 사원명, 직업, 입사일을 출력하라.
SELECT *
FROM (
    SELECT *
    FROM EMP
    WHERE hiredate BETWEEN '81/06/01' AND '81/12/31'
) E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE DNAME = 'SALES';


SELECT *
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE hiredate BETWEEN '81/06/01' AND '81/12/31'
AND D.DNAME = 'SALES';


SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;
-- 4. 1980년~1982년 사이에 입사한 각 부서별 
--입사년도별 사원 수, 부서번호, 부서명 을 출력하라.
SELECT HIREDATE,COUNT(*)
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY hiredate;

SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'), '1980', 1, 0)); 
SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'), '1980', 1, 0));

SELECT D.DEPTNO,D.DNAME,
    SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'), '1980', 1, 0))"입사 1980",
--    COUNT(DECODE(TO_CHAR(E.HIREDATE,'YYYY'),'1980',99)"입사 1980",
    SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'), '1981', 1, 0))"입사 1981",
    SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'), '1982', 1, 0))"입사 1982"
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO,D.DNAME;

SELECT D.DEPTNO,D.DNAME,
    SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'),'1980',1,0))AS 1980,
    SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'),'1981',1,0))AS 1981,
    SUM(DECODE(TO_CHAR(E.HIREDATE, 'YYYY'),'1982',1,0))AS 1982,
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO,D.DNAME;