--INNER , LEFT JOIN
--SELF JOIN

--EMP, DEPT 테이블 조인
--INNER , LEFT 조인에 따른 차이점

SELECT *
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO; -- 교집합(홍,김 미출력)

SELECT *
FROM EMP E
LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO; -- 홍,김 출력

SELECT EMPNO, ENAME, JOB, SAL, NVL(DEPTNO,99),NVL(COMM,0) AS COMM --널처리 함수. data 값이 null 값일때 임의설정값으로 처리해주기
FROM EMP;

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
--1.STUDENT 테이블에서 한번도 시험을 보지 않은 학생의 수

SELECT *
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE E.STU_NO IS NULL;

--2.STUDENT 테이블에서 한번도 시험을 보지 않은 학생의 수 + 1개만 시험본 학생들의 목록
SELECT * 
FROM STUDENT S
INNER JOIN ( 
    SELECT S.STU_NO, COUNT(*)
    FROM STUDENT S
    LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO
    HAVING COUNT(*) = 1
)E2 ON S.STU_NO = E2.STU_NO;

SELECT S.STU_NO, COUNT(S.STU_NO) AS STU_NO
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO; -- 1,2 만 구해짐

SELECT S.STU_NO, COUNT(*)
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO
HAVING COUNT(*) = 1; -- 1만 구해짐

SELECT *
FROM STUDENT S
WHERE STU_NO IN (
    SELECT S.STU_NO
    FROM STUDENT S
    LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO
    HAVING COUNT(*) = 1
);
