--1.각 학과별 평균 몸무게 구하기
SELECT STU_DEPT,ROUND(AVG(STU_WEIGHT),1) --ROUND 반올림
FROM STUDENT
 GROUP BY STU_DEPT;
--2.키가 가장 작은 학생의 값 구하기
SELECT MIN(STU_HEIGHT)
FROM STUDENT;

--3.각 학년별 평균 키 값 구하기
SELECT STU_GRADE,ROUND(AVG(STU_HEIGHT))
FROM STUDENT
GROUP BY STU_GRADE;

--4. 각 성별별 평균 키 값 구하기
SELECT STU_GENDER, ROUND(AVG(STU_HEIGHT))
FROM STUDENT
GROUP BY STU_GENDER;