--1.1 시험점수가 없는 학생들의 학번, 이름, 점수출력(점수는 0으로 출력)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.STU_NO, STU_NAME,NVL(ENR_GRADE,0)
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE ENR_GRADE IS NULL;

--1.2 시험을 1개만 본 학생들의 학번, 이름 , 점수 출력
SELECT STU_NAME,S.STU_NO,COUNT(*)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO,STU_NAME
HAVING COUNT(*) = 1;

SELECT S.STU_NO, STU_NAME,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE S.STU_NO IN(
    SELECT STU_NO
    FROM ENROL
    GROUP BY STU_NO    
    HAVING COUNT(*) = 1
);

--1-3 시험을 안보았거나 1개만 본 친구들의 학번,이름,점수 출력(시험을 안본친구는 0점으로 출력)
--테이블을 합치는방법 UNION 유니온/SUM/합치기
--컬럼의 별칭은 상위테이블을 따라간다.

SELECT S.STU_NO AS 학번 , STU_NAME AS 이름 ,NVL(ENR_GRADE,0) AS 점수 
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE ENR_GRADE IS NULL
UNION
SELECT S.STU_NO, STU_NAME,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE S.STU_NO IN(
    SELECT STU_NO
    FROM ENROL
    GROUP BY STU_NO    
    HAVING COUNT(*) = 1
);

SELECT *
FROM EMP;

--2.1급여를 1500이상 받는 사람의 사번,이름,급여,커미션 출력
SELECT EMPNO AS 사번 ,ENAME AS 이름 ,SAL AS 급여,NVL(COMM,0) AS 커미션
FROM EMP
WHERE SAL >=1500;
--2.2 커미션을 받는 사람의 사번,이름,급여,커미션 출력
SELECT EMPNO,ENAME,SAL,COMM
FROM EMP
WHERE COMM IS NOT NULL;

--위 두개 테이블 UNION 합치기 // UNION ALL

SELECT EMPNO AS 사번 ,ENAME AS 이름 ,SAL AS 급여,NVL(COMM,0) AS 커미션
FROM EMP
WHERE SAL >=1500
UNION ALL -- 중복된 결과를 모두 출력 // UNION은 중복제거
SELECT EMPNO,ENAME,SAL,COMM
FROM EMP
WHERE COMM IS NOT NULL
ORDER BY 급여 DESC;

