SELECT * FROM STUDENT2;

SELECT NAME,
    CASE WHEN GRADE = '1' THEN '신입생'
        WHEN GRADE = '2' THEN '2학년'
        WHEN GRADE = '3' THEN '3학년'
        WHEN GRADE = '4' THEN '졸업예정'
        ELSE '대학원생'
    END AS 학년정보
FROM STUDENT2;

--서진수 GRADE를 5로 변경
UPDATE STUDENT2
SET
    GRADE = 5
WHERE NAME='서진수';

--EMP테이블에서 급여가 1000이하면 'D등급'
--1001~2000 'C등급'
--2001~3000 'B등급'
--그외 'A등급'
SELECT 
    CASE WHEN SAL <= 1000 THEN 'D등급'
        WHEN SAL BETWEEN 1001 AND 2000 THEN 'C등급'
        WHEN SAL BETWEEN 2001 AND 3000 THEN 'B등급'
        ELSE 'A등급'
    END AS 급여등급
FROM EMP;

--시퀀스(sequence) 숫자가 자동적으로 증가
SELECT * FROM BOARD;

CREATE SEQUENCE TEST_SEQ  -- 게시글 셋팅 게시판
INCREMENT BY 1 -- 증가 값
START WITH 1 -- 시작 값
MINVALUE 1 -- 최소 값
MAXVALUE 100000 -- 최대 값
CYCLE -- NOCYCLE 다시 반복할지 ~ MIN 값출력
;

SELECT TEST_SEQ.NEXTVAL -- 다음 값 출력
FROM DUAL;
SELECT TEST_SEQ.CURRVAL -- 시퀀스 현재위치값 표시
FROM DUAL;

INSERT INTO BOARD VALUES (TEST_SEQ.NEXTVAL, 'HTML 기대됨', 'ㅎㅎㅎ',SYSDATE,SYSDATE,'TEST',0,2);
SELECT * FROM BOARD; 

--뷰(VIEW)

--STUDENT,ENROL, SUBJECT
--학번, 이름, 점수, 과목명
SELECT * FROM STUDENT; 
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

CREATE OR REPLACE VIEW V_STUDENT
AS 
    SELECT S.STU_NO, STU_NAME, ENR_GRADE, SUB_NAME, STU_GRADE
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
WITH READ ONLY    
    ;

SELECT * FROM V_STUDENT;

--MERGE(병합) 
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE STU_NO = '20231234';

MERGE
    INTO STUDENT S
    USING DUAL D --필수는 아니다
    ON (S.STU_NO = '20231234')
WHEN MATCHED THEN 
    UPDATE SET
        STU_DEPT = '기계'
WHEN NOT MATCHED THEN
    INSERT(STU_NO, STU_NAME, STU_DEPT)
    VALUES('20221234','홍길동','기계');

