SELECT * FROM STUDENT2;
SELECT * FROM DEPARTMENT;
SELECT * FROM PROFESSOR;

--[문항1]  PROFESSOR 테이블에서 교수들의 이메일을 아래와 같이 출력 하시오.
-- 조건 1. 전체 길이는 해당 컬럼 값의 길이
-- 조건 2. 마지막 4글자를 제외한 나머지 부분을 문자 '*'로 채워서 출력
-- 조건 3. 출력 컬럼은 교수 이름, 아래와 같이 편집된 EMAIL 컬럼

SELECT *
FROM PROFESSOR;

SELECT NAME,LPAD(SUBSTR(EMAIL,LENGTH(EMAIL)-3,LENGTH(EMAIL)),LENGTH(EMAIL),'*')  
FROM PROFESSOR;
	
--[문항2]  학부별 키(HEIGHT)가 가장 작은 학생들의 목록을 출력하시오.
-- 출력 컬럼 : 학부명, 학번, 학생 이름, 키
-- 참고 테이블 : STUDENT2, DEPARTMENT


SELECT D2.DNAME,S.STUDNO,NAME,S.HEIGHT
FROM STUDENT2 S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
INNER JOIN (
    SELECT D2.DNAME,MIN(HEIGHT) AS HEIGHT
    FROM STUDENT2 S
    INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
    INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
    GROUP BY D2.DNAME ) S2 ON S.HEIGHT = S2.HEIGHT AND D2.DNAME = S2.DNAME;
    
    
--[문항3]  직급이 정교수인 레코드의 급여 총 합과 전임강사 급여 총 합의 차이를 구하시오.
-- 참고 테이블 : PROFESSOR
SELECT * FROM PROFESSOR;

SELECT (
    (SELECT SUM(PAY)
    FROM PROFESSOR
    WHERE POSITION = '정교수')
    -
    (SELECT SUM(PAY)
    FROM PROFESSOR
    WHERE POSITION = '전임강사')
    ) AS 급여차
FROM DUAL;


--공과대학에 속한 94, 95 학번 학생들의 남녀 수를 구하는 쿼리를 작성하시오.
-- 참고테이블 : STUDENT2, DEPARTMENT
SELECT * FROM DEPARTMENT;

SELECT 
    SUM(DECODE(SUBSTR(JUMIN,7,1), '1', 1, 0))"남자"
    ,SUM(DECODE(SUBSTR(JUMIN,7,1), '2', 1, 0))"여자"
FROM( 
    SELECT *
    FROM STUDENT2 S
    INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
    INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
    INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
    WHERE SUBSTR(STUDNO,1,2)IN ('94','95') --AND D3.DNAME = '공과대학'
    )S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME= '공과대학';

SELECT *
FROM STUDENT2 S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE SUBSTR(STUDNO,1,2)IN ('94','95');


--[문항5]  공과대학에서 속한 교수들 중 가장 큰 급여를 가지는 사람과 가장 적은 급여를 가지는 사람의 교수 이름,
--소속 학과, 직급, 급여를 출력하시오
-- 참고 테이블 : PROFESSOR, DEPARTMENT
SELECT * FROM PROFESSOR;

SELECT P.NAME,D2.DNAME,POSITION,PAY
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO

INNER JOIN(
    SELECT MAX(PAY) AS MAX, MIN(PAY) AS MIN
    FROM PROFESSOR P
    INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
    INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
    INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
    WHERE D3.DNAME = '공과대학'
    )P2 ON P.PAY = P2.MAX OR P.PAY = P2.MIN
;