DELETE FROM EMP;
COMMIT;

SELECT * FROM EMP; --DEPTNO
SELECT * FROM DEPT; 
SELECT * FROM SALGRADE; -- 급여등급을 나타냄

--각 사원의 사번,이름,부서명,부서 위치 출력
SELECT EMPNO, ENAME, DNAME, LOC
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

--각 사원의 이름,급여,급여등급 출력
SELECT ENAME,SAL,GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY SAL ASC, ENAME;         -- SAL ~ 오름차순 정렬 : ORDER BY ~ ASC
--동일한 값이 있다면 두개까지 오름차순정렬가능  내림차순 정렬 : ORDER BY ~ DESC


