--JOIN (*INNER, *LEFT(RIGHT), SELF) 거의 *두개만씀
SELECT * FROM STUDENT
WHERE STU_NO = '20131001';
SELECT * FROM ENROL; --점수 테이블
SELECT * FROM SUBJECT; --과목 테이블
--20131001 김종헌 컴퓨터개론 80 시스템분석 56  

SELECT S.STU_NO, STU_NAME, ENR_GRADE,SUB_NAME
FROM STUDENT S --STUDENT의 별칭 S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO --ENROL의 별칭 E
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
WHERE ENR_GRADE >= 70 -- JOIN이 있다면 WHERE은 이후에 온다. *JOIN->WHERE->ORDER BY
ORDER BY ENR_GRADE DESC
;

-- 학생 테이블 조회
SELECT STU_DEPT, MAX(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

SELECT *
FROM STUDENT S
INNER JOIN ( --JOIN안에 테이블 & 서브쿼리 
    SELECT STU_DEPT, MAX(STU_HEIGHT) AS HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) E ON S.STU_DEPT = E.STU_DEPT AND S.STU_HEIGHT = E.HEIGHT;