--1. 각 학생들의 학번, 이름, 학과, 수강과목 수 출력
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT *
FROM STUDENT S
INNER JOIN (
    SELECT S.STU_NO, COUNT(*) AS CNT
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO
    )A ON S.STU_NO = A.STU_NO;

SELECT *
FROM STUDENT S
INNER JOIN (
    SELECT STU_NO, COUNT(*) AS 수강과목수
    FROM ENROL
    GROUP BY STU_NO
)A ON A.STU_NO = S.STU_NO
WHERE 수강과목수 > 1;

--1-1.각 학생들의 학번,이름,학과 출력. 단 1과목만 수강하는 학생들만
SELECT S.STU_NO,STU_NAME,STU_DEPT,CNT
FROM STUDENT S
INNER JOIN(
    SELECT STU_NO, COUNT(*) AS CNT
    FROM ENROL E
    GROUP BY STU_NO
    )A ON A.STU_NO = S.STU_NO
    WHERE CNT = 1;
    
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
--1-2 가장 많은 과목을 수강하고 있는 학과의 학생들 출력
SELECT STU_DEPT, SUM(CNT)
FROM STUDENT S
INNER JOIN 
    (SELECT STU_NO, COUNT(*) AS CNT
    FROM ENROL E
    GROUP BY STU_NO 
    )A ON S.STU_NO = A.STU_NO
    GROUP BY STU_DEPT;
    
--2. 기계과 학생들중 최고 점수의 학생보다 높은 점수를 받은 
--	학생들의 학번, 이름, 과목명, 점수 출력
SELECT S.STU_NO,STU_NAME,SUB_NAME,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
WHERE ENR_GRADE >
    (SELECT MAX(ENR_GRADE)
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
    WHERE STU_DEPT = '기계'
    );

--	
--(EMP, DEPT, SALGRADE 테이블)
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;
--3. 각 부서별 급여 등급 평균 구하기
SELECT DEPTNO, ROUND(AVG(GRADE))
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY DEPTNO;

--3. 부서명, 평균 등급 출력
SELECT DNAME, ROUND(AVG(S.GRADE))
FROM EMP E
INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY DNAME;

SELECT DNAME, G_AVG
FROM DEPT D
INNER JOIN (
    SELECT DEPTNO, ROUND(AVG(GRADE)) AS G_AVG
    FROM EMP E
    INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    GROUP BY DEPTNO
    ) A ON A.DEPTNO = D.DEPTNO;

--4. 각 부서별 급여 등급이 3등급 이상인 사람의 수 구하기
SELECT D.DEPTNO,DNAME, COUNT(*)
FROM EMP E
INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE S.GRADE>= '3'
GROUP BY D.DEPTNO,DNAME;

    SELECT E.ENAME -- 3등급 이상인 사람명단
    FROM EMP E
    INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO
    INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    WHERE S.GRADE >= 3;
--    GROUP BY D.DNAME;

--4-1. 각 부서별 급여가 2500인 사람의 수 구하기 - >부서명 출력
SELECT D.DEPTNO,DNAME, COUNT(*)
FROM EMP E
INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO
WHERE SAL>=2500
GROUP BY D.DEPTNO,DNAME;

--5. 평균급여 등급이 가장 높은 부서와 낮은 부서와의 등급 차이 구하기

SELECT MAX(SAL_AVG) - MIN(SAL_AVG)
FROM (
    SELECT DEPTNO, ROUND(AVG(GRADE),1) AS SAL_AVG
    FROM EMP E
    INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    GROUP BY DEPTNO --평균 등급
);
